spring:
    datasource:
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 5
        password: 1234
        url: jdbc:postgresql://localhost:5432/companies
        username: admin